#!/usr/bin/env bash
# Hook: Session Summarizer (PreCompact)
# Rule 10: Checkpoint before compaction — preserve context across session breaks

set -euo pipefail

CHECKPOINT_DIR="${CLAUDE_CHECKPOINT_DIR:-.claude/logs/checkpoints}"
mkdir -p "$CHECKPOINT_DIR"

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
DATESTAMP=$(date +"%Y%m%d_%H%M%S")
OUTPUT_FILE="$CHECKPOINT_DIR/pre-compact-$DATESTAMP.md"

RECENT_LOG="$CHECKPOINT_DIR/session_$(date +%Y%m%d).log"
RECENT_LINES=""
if [[ -f "$RECENT_LOG" ]]; then
  RECENT_LINES=$(tail -20 "$RECENT_LOG" 2>/dev/null || echo "No log entries yet.")
fi

cat > "$OUTPUT_FILE" << EOF
# Pre-Compact Checkpoint
**Timestamp:** $TIMESTAMP
**Session Log:** $DATESTAMP

## Recent Tool Calls (last 20)
\`\`\`
${RECENT_LINES:-No tool calls logged yet}
\`\`\`

## Rule 10 Checkpoint Template
*(Claude: fill this out before context is compacted)*

### ✅ DONE
- 

### ✔️ VERIFIED
- 

### ⏳ NEXT
- 

### ⚠️ RISKS / OPEN QUESTIONS
- 

### 📊 TOKEN BUDGET
- Task tokens used: 
- Session tokens used: 

---
*Generated by PreCompact/01-session-summarizer.sh*
EOF

echo "📋 Pre-compact checkpoint saved: $OUTPUT_FILE" >&2
echo "   Review and fill in the checkpoint template before context is compacted." >&2

exit 0
